name: pepecoin-mainnet

services:
  core:
    image: pepeenthusiast/pepecoin-core:latest
    restart: unless-stopped
    command:
        -printtoconsole
        -server=1
        -txindex=1
        -rpcallowip=0.0.0.0/0
        -rpcuser=rpc
        -rpcpassword=rpcp
    volumes:
        - core_data:/home/pepecoin/.pepecoin
  electrs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    command: |
      -vv
      --jsonrpc-import
      --precache-stats
      --precache-utxos
      --address-search
      --index-unspendables
      --daemon-rpc-addr core:33873
      --daemon-dir /.pepecoin
      --cookie rpc:rpcp
      --db-dir /electrs
      --cors '*'
    volumes:
    - core_data:/.pepecoin
    - electrs_data:/electrs

volumes:
  core_data:
  electrs_data: